    <link href="https://fonts.googleapis.com/css?family=Oleo+Script:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Teko:400,700" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <!-- <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script> -->
    <link rel="stylesheet" type="text/css" href="css/style.css">

    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <!-- <script src="js/jquery-3.2.1.min.js" type="text/javascript" charset="utf-8"></script> -->




    <script>
    function enviar(){
            swal({
                text: "Mensagem eviada com sucesso!",
                icon: "success",
                });

            return false
            }


    </script>

<?php
require_once "topo.phtml";
 ?>
<section id="contact">
            <div class="section-content">
                <h1 class="section-header">Contatar<span class="content-header wow fadeIn " data-wow-delay="0.2s" data-wow-duration="2s">  Felipe Sales</span></h1>
                <h3>...</h3>
            </div>
            <div class="contact-section">
            <div class="container">
                <form>
                    <div class="col-md-6 form-line">
                        <div class="form-group-contact">
                            <label class="" for="exampleInputUsername">Nome</label>
                            <input id="nome" type="text" class="form-control"  placeholder="">
                        </div>
                        <div class="form-group-contact">
                            <label class="" for="exampleInputEmail">Email</label>
                            <input id="email" type="email" class="form-control" placeholder="">
                        </div>
                        <div class="form-group">

                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group-contact">

                            <label class="" for="telephone">Assunto</label>
                            <input id="" type="tel" class="form-control" placeholder=" "><br/>
                            <label class="" for ="description"> Mensagem</label>
                            <textarea  class="form-control contact" id="description" placeholder="Escreva Sua Mensagem"></textarea>
                        </div>
                        <div>
                            <button  onclick="enviar()" type="button" class="btn btn-default submit"><i class="fa fa-paper-plane" aria-hidden="true"></i>  Enviar Mensagem</button>
                        </div>
                    </div>
                </form>
            </div>
        </section>