
        <div id="msg-erro" class="alert alert-danger hidden" role="alert">
          This is a danger alert—check it out!
        </div>
            <!--Inicio do Cadastrar-->
            <form id="form-cad">
                    <div class="form-group">
                        <label for="exampleInputPassword1">Nome</label>
                        <input name="nome" type="text" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Email </label>
                        <input name="email" type="email" class="form-control">
                    </div>
                    <button  type="submit" class="btn btn-primary">Salvar</button>
            </form>
              <!--Fim do Cadastrar-->
        <script src="js/jquery-3.2.1.min.js" type="text/javascript" charset="utf-8"></script>
        <script src="dist/jquery.validate.min.js"></script>



            <script>
                $(document).ready(function(){
                    $("#form-cad").validate({
                           rules : {
                                 nome:{
                                        required:true,
                                        minlength:3
                                 },
                                 email:{
                                        required:true
                                 }
                           },
                           messages:{
                                 nome:{
                                        required:"Por favor, informe seu nome",
                                        minlength:"O nome deve ter pelo menos 3 caracteres"
                                 },
                                 email:{
                                        required:"É necessário informar um email"
                                 }
                           }
                    });


Read more: http://www.linhadecodigo.com.br/artigo/3706/jquery-validate-validacao-de-formularios-html.aspx#ixzz4z4AAJd5D

                    // $("#form-cad").submit(function(){

                    //     var form = document.getElementById('form-cad')

                    //         if (form.nome.value == ""){
                    //             $("#msg-erro").text("Preencha o campo nome")
                    //             $("#msg-erro").removeClass('hidden')
                    //             return false
                    //         }

                    //         if (form.email.value == ""){
                    //             $("#msg-erro").text("Preencha o campo Email")
                    //             $("#msg-erro").removeClass('hidden')
                    //             return false
                    //         }

                    //         $("#msg-erro").addClass('hidden')

                        $.ajax({
                            url: 'cadastrar_usuario.php',
                            data: $(this).serialize(),
                            success: function(data){
                                $("#exampleModal").modal('toggle')
                            }
                        })
                        return false
                    })
                })
            </script>

