
        <!-- <div id="msg-erro" class="alert alert-danger hidden" role="alert">
          This is a danger alert—check it out!
        </div> -->
            <!--Inicio do Cadastrar-->

            <form id="form-cad" class="formulario">
                    <div class="form-group">
                        <label class="label" for="exampleInputPassword1">Nome</label>
                        <input id="nome" name="nome" type="text" class="form-control" placeholder="Digite seu nome">
                         <div  class="invalid-feedback">Preencha o campo Nome</div>
                    </div>
                    <div class="form-group">
                        <label class="label" for="exampleInputEmail1">Email </label>
                        <input id="email" name="email" type="text" class="form-control" placeholder="Digite seu email">
                        <div id="erro-email" class="invalid-feedback">Preencha o campo Email</div>
                    </div>
                    <button  type="submit" class="btn btn-primary">Salvar</button>
            </form>
              <!--Fim do Cadastrar-->
        <!-- <script src="js/jquery-3.2.1.min.js" type="text/javascript" charset="utf-8"></script>
        <script src="dist/jquery.validate.min.js"></script> -->



            <script>
                $(document).ready(function(){
                    /*$("#email").change(function(){
                        alert("mudou o campo")
                    })*/

                    $("#form-cad").submit(function(){

                        var form = document.getElementById('form-cad')
                        var filtroEmail = /^([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$/i;
                        var formValido = true

                            if (form.nome.value == ""){
                                formValido = false
                                $("#nome").addClass("is-invalid")
                                // $("#msg-erro").text("Preencha o campo nome")
                                // $("#msg-erro").removeClass('hidden')
                            }else {
                                $("#nome").removeClass("is-invalid")
                                $("#nome").addClass("campo-valido")
                            }

                            if (form.email.value == ""){
                                formValido = false
                                $("#erro-email").text("Preencha o campo Email")
                                $("#email").addClass('is-invalid')
                                // $("#msg-erro").text("Preencha o campo Email")
                                // $("#msg-erro").removeClass('hidden')
                            }else if(filtroEmail.test(form.email.value) == false){
                                formValido = false
                                $("#erro-email").text("O email é inválido.")
                                $("#email").addClass('is-invalid')
                            }else{
                                $("#email").removeClass("is-invalid")
                                $("#email").addClass("campo-valido")
                            }

                            if (formValido == false){
                                return false
                            }

                        $.ajax({
                            url: 'cadastrar_usuario.php',
                            dataType: 'json',
                            data: $(this).serialize(),
                            success: function(data){
                                if (data.type == 'error') {
                                    $("#erro-email").text(data.msg)
                                    $("#email").addClass('is-invalid')
                                } else {
                                    $("#exampleModal").modal('toggle')
                                }
                            }
                        })
                        return false
                    })
                })
            </script>

